---
title: "Untitled"
author: "Artina Neuteboom (2188031)"
date: "2026-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(dplyr)
library(tibble)

css_lookup <- tribble(
  ~police_category, ~home_office_code, ~sub_offence, ~ons_weight, ~approx_frequency,

  # Violence and sexual offences
  "Violence and sexual offences", "8N",  "Assault with injury", 203, 45,
  "Violence and sexual offences", "105A", "Assault without injury", 13, 20,
  "Violence and sexual offences", "8F",  "Inflicting GBH without intent", 353, 8,
  "Violence and sexual offences", "8G",  "Actual bodily harm and other injury", 145, 10,
  "Violence and sexual offences", "8Q",  "Stalking", 99, 4,
  "Violence and sexual offences", "8L",  "Harassment", 40, 5,
  "Violence and sexual offences", "8U",  "Controlling and coercive behaviour", 392, 2,
  "Violence and sexual offences", "3B",  "Threats to kill", 311, 1,
  "Violence and sexual offences", "19C", "Rape of a female aged 16 or over", 3163, 1,
  "Violence and sexual offences", "20A", "Sexual assault on a female aged 13 and over", 498, 2,
  "Violence and sexual offences", "20B", "Sexual assault on a female child under 13", 1295, 1,
  "Violence and sexual offences", "88B", "Other miscellaneous sexual offences", 96, 1,

  # Anti-social behaviour
  "Anti-social behaviour", "9A", "Public fear, alarm or distress", 8, 80,
  "Anti-social behaviour", "9B", "Racially or religiously aggravated public fear, alarm or distress", 14, 20,

  # Burglary
  "Burglary", "28/28A", "Burglary in a dwelling", 564, 60,
  "Burglary", "29", "Aggravated burglary in a dwelling", 2459, 2,
  "Burglary", "30/30A", "Burglary in a building other than a dwelling", 150, 37,
  "Burglary", "31", "Aggravated burglary in a building other than a dwelling", 1856, 1,

  # Robbery
  "Robbery", "34B", "Robbery of personal property", 994, 75,
  "Robbery", "34A", "Robbery of business property", 994, 25,

  # Vehicle crime
  "Vehicle crime", "45", "Theft from a vehicle", 35, 55,
  "Vehicle crime", "48", "Theft or unauthorised taking of a motor vehicle", 143, 30,
  "Vehicle crime", "37.2", "Aggravated vehicle taking", 55, 10,
  "Vehicle crime", "126", "Vehicle interference", 9, 5,

  # Shoplifting
  "Shoplifting", "46", "Shoplifting", 13, 100,

  # Theft from the person
  "Theft from the person", "39", "Theft from the person", 87, 100,

  # Other theft
  "Other theft", "49", "Other theft", 43, 50,
  "Other theft", "40", "Theft in a dwelling other than from an automatic machine or meter", 52, 20,
  "Other theft", "41", "Theft by an employee", 47, 10,
  "Other theft", "35", "Blackmail", 774, 2,
  "Other theft", "54", "Handling stolen goods", 70, 10,
  "Other theft", "49A", "Making off without payment", 7, 8,

  # Criminal damage and arson
  "Criminal damage and arson", "58A", "Criminal damage to a dwelling", 9, 35,
  "Criminal damage and arson", "58C", "Criminal damage to a vehicle", 9, 30,
  "Criminal damage and arson", "58B", "Criminal damage to a building other than a dwelling", 9, 15,
  "Criminal damage and arson", "58D", "Other criminal damage", 9, 10,
  "Criminal damage and arson", "58J", "Racially or religiously aggravated criminal damage", 13, 5,
  "Criminal damage and arson", "56B", "Arson not endangering life", 200, 4,
  "Criminal damage and arson", "56A", "Arson endangering life", 902, 1,

  # Drugs
  "Drugs", "92E", "Possession of cannabis", 2, 50,
  "Drugs", "92D", "Possession of controlled drugs excluding cannabis", 9, 25,
  "Drugs", "92C", "Other drug offences", 12, 10,
  "Drugs", "92A", "Trafficking in controlled drugs", 667, 15,

  # Possession of weapons
  "Possession of weapons", "10D", "Possession of article with blade or point", 71, 45,
  "Possession of weapons", "10C", "Possession of other weapons", 61, 25,
  "Possession of weapons", "8B", "Possession of weapons", 85, 15,
  "Possession of weapons", "10B", "Possession of firearms offences", 555, 8,
  "Possession of weapons", "10A", "Possession of firearms with intent", 703, 5,
  "Possession of weapons", "90", "Other knives offences", 9, 2,

  # Public order
  "Public order", "9A", "Public fear, alarm or distress", 8, 60,
  "Public order", "9B", "Racially or religiously aggravated public fear, alarm or distress", 14, 20,
  "Public order", "65", "Violent disorder", 356, 10,
  "Public order", "66", "Other offences against the State or public order", 69, 10,

  # Bicycle theft
  "Bicycle theft", "44", "Theft or unauthorised taking of a pedal cycle", 19, 100,

  # Other crime
  "Other crime", "61", "Other forgery", 148, 20,
  "Other crime", "79", "Perverting the course of justice", 184, 15,
  "Other crime", "33", "Going equipped for stealing", 37, 20,
  "Other crime", "67", "Perjury", 116, 10,
  "Other crime", "99", "Other indictable or triable-either-way offences", 186, 20,
  "Other crime", "59", "Threat etc. to commit criminal damage", 59, 15
)

```


```{r}
css_table <- css_lookup %>%
  group_by(police_category) %>%
  summarise(
    weighted_avg_css = round(sum(ons_weight * approx_frequency) / sum(approx_frequency)),
    n_sub_offences = n(),
    .groups = "drop"
  )

print(css_table)
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

